import { getTopNotifications } from "./notificationService.js";

const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJ2cDA3NjZAc3JtaXN0LmVkdS5pbiIsImV4cCI6MTc3NzcwMTY5NywiaWF0IjoxNzc3NzAwNzk3LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiY2FkZDIxMTctZTEwZi00Y2Y5LWFlNzgtMDZmN2M3NDgwOGRkIiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoidmlzaG51dmFyZGhhbiBwb2xhIiwic3ViIjoiMWZiMDdkYTQtYzRkMC00NGJlLWIwMjYtNmNhYTg3YmZmMDMxIn0sImVtYWlsIjoidnAwNzY2QHNybWlzdC5lZHUuaW4iLCJuYW1lIjoidmlzaG51dmFyZGhhbiBwb2xhIiwicm9sbE5vIjoicmEyMzExMDI2MDIwMTU3IiwiYWNjZXNzQ29kZSI6IlFrYnB4SCIsImNsaWVudElEIjoiMWZiMDdkYTQtYzRkMC00NGJlLWIwMjYtNmNhYTg3YmZmMDMxIiwiY2xpZW50U2VjcmV0IjoiekJocGZKaGR1bk11dlpwRCJ9.zPk17WtLsRwjvuWNBMTuT-v0qJLdbINI4DcG1A9IoBI"
getTopNotifications(TOKEN).then(data => {
  console.log("Top Notifications:", data);
});